### ISSUE TITLE
deploy the fabric with bft-smart orderer using k8s

### ISSUE THREAD

**Issue by dzqoo** [jcs47/hyperledger-bftsmart#17]
First of all ，thank you for offering such a good idea！
When deploying the fabric with yours orderingnode image and frontend image using k8s， I encounter some problems.
1、I deploy every components with k8s，and everything goes well；
2、When I create channel with go sdk，it seems nothing is wrong；
3、But When I join the peers to channel，I got the following errors：
 （1）orderernode（frontend） error logs 
`2018-08-02 12:36:27.290 UTC [common/configtx] addToMap -> DEBU 4cf Adding to config map: [Policy] /Channel/Readers
2018-08-02 12:36:27.290 UTC [common/configtx] addToMap -> DEBU 4d0 Adding to config map: [Policy] /Channel/Writers
2018-08-02 12:36:27.291 UTC [common/configtx] addToMap -> DEBU 4d1 Adding to config map: [Policy] /Channel/Admins
2018-08-02 12:36:27.291 UTC [common/capabilities] Supported -> DEBU 4d2 Orderer capability V1_1 is supported and is enabled
2018-08-02 12:36:27.291 UTC [common/capabilities] Supported -> DEBU 4d3 Channel capability V1_1 is supported and is enabled
2018-08-02 12:36:27.292 UTC [orderer/common/broadcast] Handle -> DEBU 4d4 [channel: mychannel] Broadcast has successfully enqueued message of type CONFIG_UPDATE from 172.29.101.151:58804
2018-08-02 12:36:27.293 UTC [orderer/common/broadcast] Handle -> DEBU 4d5 Received EOF from 172.29.101.151:58804, hangup
2018-08-02 12:36:27.293 UTC [orderer/common/server] func1 -> DEBU 4d6 Closing Broadcast stream
2018-08-02 12:36:37.299 UTC [orderer/common/server] Deliver -> DEBU 4d7 Starting new Deliver handler
2018-08-02 12:36:37.299 UTC [common/deliver] Handle -> DEBU 4d8 Starting new deliver loop for 172.29.101.151:58920
2018-08-02 12:36:37.300 UTC [common/deliver] Handle -> DEBU 4d9 Attempting to read seek info message from 172.29.101.151:58920
2018-08-02 12:36:37.300 UTC [common/deliver] deliverBlocks -> DEBU 4da Rejecting deliver for 172.29.101.151:58920 because channel mychannel not found
2018-08-02 12:36:37.300 UTC [common/deliver] Handle -> DEBU 4db Waiting for new SeekInfo from 172.29.101.151:58920
2018-08-02 12:36:37.300 UTC [common/deliver] Handle -> DEBU 4dc Attempting to read seek info message from 172.29.101.151:58920
2018-08-02 12:36:37.304 UTC [common/deliver] Handle -> WARN 4dd Error reading from 172.29.101.151:58920: rpc error: code = Canceled desc = context canceled
2018-08-02 12:36:37.304 UTC [orderer/common/server] func1 -> DEBU 4de Closing Deliver stream`
Where the 172.29.101.151 is the ip of mine go sdk client；
（2）ordereringnode error logs
`Aug 02, 2018 12:36:13 PM bft.BFTNode executeSingle
INFO: Purging blockcutter for channel testchainid
bft.BFTCommon$BFTException: Error while processing envelopes.
	at bft.BFTNode.processEnvelopes(BFTNode.java:792)
	at bft.BFTNode.executeSingle(BFTNode.java:566)
	at bft.BFTNode.appExecuteBatch(BFTNode.java:436)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:87)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:68)
	at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:444)
	at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:300)
	at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:231)
	Suppressed: java.lang.NullPointerException
		at bft.BFTNode.processEnvelopes(BFTNode.java:677)
		... 7 more`
（3）peer error logs
`2018-08-02 12:36:37.312 UTC [endorser] ProcessProposal -> DEBU 238 Entering: Got request from 172.29.101.151:42306
2018-08-02 12:36:37.312 UTC [protoutils] ValidateProposalMessage -> DEBU 239 ValidateProposalMessage starts for signed proposal 0xc4218d93b0
2018-08-02 12:36:37.312 UTC [protoutils] validateChannelHeader -> DEBU 23a validateChannelHeader info: header type 3
2018-08-02 12:36:37.312 UTC [protoutils] checkSignatureFromCreator -> DEBU 23b begin
2018-08-02 12:36:37.312 UTC [protoutils] checkSignatureFromCreator -> DEBU 23c creator is &{Org1MSP 4671e4dd33948a58b5ba76a38943bf7395f86d1ffec5bd6c6bb19b15ffe166c3}
2018-08-02 12:36:37.313 UTC [protoutils] checkSignatureFromCreator -> DEBU 23d creator is valid
2018-08-02 12:36:37.313 UTC [protoutils] checkSignatureFromCreator -> DEBU 23e exits successfully
2018-08-02 12:36:37.313 UTC [protoutils] validateChaincodeProposalMessage -> DEBU 23f validateChaincodeProposalMessage starts for proposal 0xc4218bb090, header 0xc4218d9740
2018-08-02 12:36:37.313 UTC [protoutils] validateChaincodeProposalMessage -> DEBU 240 validateChaincodeProposalMessage info: header extension references chaincode name:"lscc" 
2018-08-02 12:36:37.313 UTC [endorser] preProcess -> DEBU 241 [][cc626d50] processing txid: cc626d5087f0881fe5ee2252b40d3a20f348184a173db667540107598e90e37c
2018-08-02 12:36:37.313 UTC [endorser] simulateProposal -> DEBU 242 [][cc626d50] Entry chaincode: name:"lscc" 
2018-08-02 12:36:37.313 UTC [endorser] callChaincode -> DEBU 243 [][cc626d50] Entry chaincode: name:"lscc"  version: 1.1.1
2018-08-02 12:36:37.313 UTC [ccprovider] NewCCContext -> DEBU 244 NewCCCC (chain=,chaincode=lscc,version=1.1.1,txid=cc626d5087f0881fe5ee2252b40d3a20f348184a173db667540107598e90e37c,syscc=true,proposal=0xc4218bb090,canname=lscc:1.1.1
2018-08-02 12:36:37.313 UTC [chaincode] Launch -> DEBU 245 chaincode is running(no need to launch) : lscc:1.1.1
2018-08-02 12:36:37.313 UTC [chaincode] Execute -> DEBU 246 Entry
2018-08-02 12:36:37.313 UTC [chaincode] Execute -> DEBU 247 chaincode canonical name: lscc:1.1.1
2018-08-02 12:36:37.314 UTC [chaincode] sendExecuteMessage -> DEBU 248 [cc626d50]Inside sendExecuteMessage. Message TRANSACTION
2018-08-02 12:36:37.314 UTC [chaincode] setChaincodeProposal -> DEBU 249 Setting chaincode proposal context...
2018-08-02 12:36:37.314 UTC [chaincode] setChaincodeProposal -> DEBU 24a Proposal different from nil. Creating chaincode proposal context...
2018-08-02 12:36:37.314 UTC [chaincode] sendExecuteMessage -> DEBU 24b [cc626d50]sendExecuteMsg trigger event TRANSACTION
2018-08-02 12:36:37.314 UTC [chaincode] processStream -> DEBU 24c [cc626d50]Move state message TRANSACTION
2018-08-02 12:36:37.314 UTC [chaincode] handleMessage -> DEBU 24d [cc626d50]Fabric side Handling ChaincodeMessage of type: TRANSACTION in state ready
2018-08-02 12:36:37.314 UTC [chaincode] filterError -> DEBU 24e Ignoring NoTransitionError: no transition
2018-08-02 12:36:37.314 UTC [chaincode] processStream -> DEBU 24f [cc626d50]sending state message TRANSACTION
2018-08-02 12:36:37.314 UTC [shim] func1 -> DEBU 250 [cc626d50]Received message TRANSACTION from shim
2018-08-02 12:36:37.314 UTC [shim] handleMessage -> DEBU 251 [cc626d50]Handling ChaincodeMessage of type: TRANSACTION(state:ready)
2018-08-02 12:36:37.314 UTC [shim] beforeTransaction -> DEBU 252 [cc626d50]Received TRANSACTION, invoking transaction on chaincode(Src:ready, Dst:ready)
2018-08-02 12:36:37.315 UTC [shim] func1 -> DEBU 253 [cc626d50]Transaction completed. Sending COMPLETED
2018-08-02 12:36:37.315 UTC [shim] func1 -> DEBU 254 [cc626d50]Move state message COMPLETED
2018-08-02 12:36:37.315 UTC [shim] handleMessage -> DEBU 255 [cc626d50]Handling ChaincodeMessage of type: COMPLETED(state:ready)
2018-08-02 12:36:37.315 UTC [shim] func1 -> DEBU 256 [cc626d50]send state message COMPLETED
2018-08-02 12:36:37.315 UTC [chaincode] processStream -> DEBU 257 [cc626d50]Received message COMPLETED from shim
2018-08-02 12:36:37.315 UTC [chaincode] handleMessage -> DEBU 258 [cc626d50]Fabric side Handling ChaincodeMessage of type: COMPLETED in state ready
2018-08-02 12:36:37.315 UTC [chaincode] handleMessage -> DEBU 259 [cc626d5087f0881fe5ee2252b40d3a20f348184a173db667540107598e90e37c]HandleMessage- COMPLETED. Notify
2018-08-02 12:36:37.315 UTC [chaincode] notify -> DEBU 25a notifying Txid:cc626d5087f0881fe5ee2252b40d3a20f348184a173db667540107598e90e37c, channelID:
2018-08-02 12:36:37.315 UTC [chaincode] Execute -> DEBU 25b Exit
2018-08-02 12:36:37.315 UTC [endorser] callChaincode -> DEBU 25c [][cc626d50] Exit
2018-08-02 12:36:37.315 UTC [endorser] simulateProposal -> DEBU 25d [][cc626d50] Exit
2018-08-02 12:36:37.315 UTC [endorser] ProcessProposal -> DEBU 25e Exit: request from%!(EXTRA string=172.29.101.151:42306)
2018-08-02 12:36:37.331 UTC [endorser] ProcessProposal -> DEBU 25f Entering: Got request from 172.29.101.151:42312
2018-08-02 12:36:37.331 UTC [protoutils] ValidateProposalMessage -> DEBU 260 ValidateProposalMessage starts for signed proposal 0xc42151b5f0
2018-08-02 12:36:37.331 UTC [protoutils] validateChannelHeader -> DEBU 261 validateChannelHeader info: header type 3
2018-08-02 12:36:37.331 UTC [protoutils] checkSignatureFromCreator -> DEBU 262 begin
2018-08-02 12:36:37.331 UTC [protoutils] ValidateProposalMessage -> WARN 263 channel [mychannel]: MSP error: channel doesn't exist
2018-08-02 12:36:37.331 UTC [endorser] ProcessProposal -> DEBU 264 Exit: request from%!(EXTRA string=172.29.101.151:42312)`
（4）mine go sdk client error logs
`unable to initialize the Fabric SDK:org peers failed to join the channel:genesis block retrieval failed:SendEnvelope failed:error returned from orderer service :error status from ordering service NOT_FOUND`

Here is mine config file :
1、configtx
 Profiles:
        TwoOrgsOrdererGenesis:
            Capabilities:
                <<: *ChannelCapabilities
            Orderer:
                <<: *OrdererDefaults
                OrdererType: bftsmart
                Organizations:
                    - *OrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                SampleConsortium:
                    Organizations:
                        - *Org1
                        - *Org2
        TwoOrgsChannel:
            Consortium: SampleConsortium
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Org1
                    - *Org2
                Capabilities:
                    <<: *ApplicationCapabilities
    Organizations:
        - &OrdererOrg
            Name: OrdererOrg
            ID: OrdererMSP
            MSPDir: crypto-config/ordererOrganizations/example.com/msp
        - &Org1
            Name: Org1MSP
            ID: Org1MSP
            MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
            AnchorPeers:
                - Host: peer0.org1.example.com
                  Port: 7051
        - &Org2
            Name: Org2MSP
            ID: Org2MSP
            MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
            AnchorPeers:
                - Host: peer0.org2.example.com
                  Port: 7051
    Orderer: &OrdererDefaults
        OrdererType: kafka
        Addresses:
            - orderer.example.com:7050
        BatchTimeout: 20s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 98 MB
            PreferredMaxBytes: 512 KB
        BFTsmart:
            ConnectionPoolSize: 20
            RecvPort: 9999 
        Kafka:
            Brokers:
                - service-kafka-1:9092
                - service-kafka-2:9092
                - service-kafka-3:9092
        Organizations:
    Application: &ApplicationDefaults
        Organizations:
    Capabilities:
        Global: &ChannelCapabilities
            V1_1: true
        Orderer: &OrdererCapabilities
            V1_1: true
        Application: &ApplicationCapabilities
            V1_1: true
2、peer config（my peer is hyperledger/fabric1.1.1）
` - name: "CORE_PEER_NETWORKID"
          value: "nid1"
        - name: "CORE_CHAINCODE_STARTUPTIMEOUT"
          value: 300s
        - name: "CORE_CHAINCODE_DEPLOYTIMEOUT"
          value: 300s
        - name: "GODEBUG"
          value: "netdns=go"
        - name: "CORE_PEER_ID"
          value: "peer0.org1.example.com"
        - name: "CORE_PEER_ADDRESS"
          value: "peer0.org1.example.com:7051"
        - name: "CORE_PEER_ADDRESSAUTODETECT"
          value: "true"
        - name: "CORE_PEER_TLS_SERVERHOSTOVERRIDE"
          value: "%(hostname).peer"
        - name: "CORE_PEER_CHAINCODEADDRESS"
          value: "peer0.org1.example.com:7052"
        - name: "CORE_PEER_GOSSIP_EXTERNALENDPOINT"
          value: "peer0.org1.example.com:7051"
        - name: "CORE_PEER_LOCALMSPID"
          value: "Org1MSP"
        - name: "CORE_VM_ENDPOINT"
          value: "unix:///host/var/run/docker.sock"
        - name: "CORE_LOGGING_LEVEL"
          value: "DEBUG"
        - name: "CORE_PEER_TLS_ENABLED"
          value: "true"
        - name: "CORE_PEER_GOSSIP_USELEADERELECTION"
          value: "true"
        - name: "CORE_PEER_GOSSIP_ORGLEADER"
          value: "false"
        - name: "CORE_PEER_PROFILE_ENABLED"
          value: "true"
        - name: "CORE_PEER_TLS_CERT_FILE"
          value: "/opt/peer/peers/peer0.org1.example.com/tls/server.crt"
        - name: "CORE_PEER_TLS_KEY_FILE"
          value: "/opt/peer/peers/peer0.org1.example.com/tls/server.key"
        - name: "CORE_PEER_TLS_ROOTCERT_FILE"
          value: "/opt/peer/peers/peer0.org1.example.com/tls/ca.crt"
        - name: "CORE_LEDGER_STATE_STATEDATABASE"
          value: "CouchDB"
        - name: "CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS"
          value: "service-couchdb-1:5984"
        - name: "CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME"
          value: "admin"
        - name: "CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD"
          value: "admin"
        volumeMounts:
        - name: peer-1
          mountPath: /opt/peer
        - name: var
          mountPath: /host/var/run/docker.sock
        - name: var
          mountPath: /var/run/docker.sock
      volumes:
      - name: peer-1
        persistentVolumeClaim:
          claimName: org1-fabric-init-0
      - name: var
        hostPath:
          path: /var/run/docker.sock`

Do you know what is wrong with my deploy?
I guess  whether it is because the config of my orderer ,that is configtx.yaml,which is quite different from yours.
Look forward to your favourable reply...

**Comment by jcs47** [comment]
I tried to figure out where that null-pointer exception was happening, but unfortunately I already made new commits that rendered the stack trace out-dated. But I will try to reproduce the problem on my own with your configuration. Whatever it is, it is probably not exclusive to k8s.

Did you only supplied a new configuration to the peer via environment variables and used your own configtx.yaml file , or did you also fiddled with the the contents of orderer.yaml at the frontend? Also, what is your configuration for stuff specific to bftsmart and the whole ordering service, i.e, the configuration files contained in the "config" folder for the images of the nodes and frontends?
