### ISSUE TITLE
problem about orderingnode 1

### ISSUE THREAD

**Issue by dzqoo** [jcs47/hyperledger-bftsmart#27]
Hello !
I got the problem below When I started orderingnode 1:
2018-09-04 12:43:44.246 [main] INFO  bft.BFTNode - Starting up ordering node with system channel syschannel
2018-09-04 12:43:44.252 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-09-04 12:43:44.252 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
-- Creating current view from configuration file
Sep 04, 2018 12:43:44 PM bftsmart.tom.ServiceReplica init
SEVERE: null
java.lang.NullPointerException
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:86)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:63)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:152)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:140)
	at bft.BFTNode.<init>(BFTNode.java:164)
	at bft.BFTNode.main(BFTNode.java:255)

Exception in thread "main" java.lang.RuntimeException: Unable to build a communication system.
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:155)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:140)
	at bft.BFTNode.<init>(BFTNode.java:164)
	at bft.BFTNode.main(BFTNode.java:255)

Do you know the reason of it?

**Comment by jcs47** [comment]
The exception that is showing is popping up from a part of the code that now is just is just a comment line. Try to reproduce the error with the latest code.
