### ISSUE TITLE
can't reconfigure the ordernodes

### ISSUE THREAD

**Issue by learnergo** [jcs47/hyperledger-bftsmart#31]
Hello, I want to apply this project in my real deployment and I have successfully deployed a fabric-net.
But before reaching this,I must confirm that ordernodes or fronteds can be added or removed. Obviously，I'm in trouble.

First,I think there is something wrong in " reconfigure.sh". 
The content should be "java -cp bin/*:lib/* bft.util.FabricVMServices $@".

So I get follow results:
```
root@771b9da76bbb:/etc/bftsmart-orderer# ./reconfigure.sh 0
####Tpp Service[Disjoint]####
2018-10-12 10:40:04.358 [main] INFO  b.r.ServerViewController - Using view stored on disk
2018-10-12 10:40:04.872 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 0 at bft.node.0/172.23.0.4:11000
2018-10-12 10:40:04.895 [nioEventLoopGroup-2-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:04.897 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 1 at bft.node.1/172.23.0.2:11000
2018-10-12 10:40:04.904 [nioEventLoopGroup-2-2] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:04.905 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 2 at bft.node.2/172.23.0.3:11000
2018-10-12 10:40:04.907 [nioEventLoopGroup-2-3] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:04.908 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 3 at bft.node.3/172.23.0.5:11000
2018-10-12 10:40:04.912 [nioEventLoopGroup-2-4] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:04.914 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 4 at bft.node.4/172.23.0.12:11000
2018-10-12 10:40:04.916 [nioEventLoopGroup-2-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:15.165 [nioEventLoopGroup-2-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - re-connecting to replica 0 at bft.node.0/172.23.0.4:11000
2018-10-12 10:40:15.168 [nioEventLoopGroup-2-2] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:40:44.881 [main] INFO  bftsmart.tom.ServiceProxy - ###################TIMEOUT#######################
2018-10-12 10:40:44.882 [main] INFO  bftsmart.tom.ServiceProxy - Reply timeout for reqId=0, Replies received: 3
Exception in thread "main" java.lang.NullPointerException
	at bftsmart.reconfiguration.ViewManager.executeUpdates(ViewManager.java:115)
	at bftsmart.reconfiguration.VMServices.execute(VMServices.java:68)
	at bftsmart.reconfiguration.VMServices.removeServer(VMServices.java:62)
	at bft.util.FabricVMServices.main(FabricVMServices.java:51)
```
```
^Croot@771b9da76bbb:/etc/bftsmart-orderer# ./reconfigure.sh 4 bft.node.4 11000
####Tpp Service[Join]####
2018-10-12 10:42:07.736 [main] INFO  b.r.ServerViewController - Using view stored on disk
2018-10-12 10:42:08.228 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 0 at bft.node.0/172.23.0.4:11000
2018-10-12 10:42:08.246 [nioEventLoopGroup-2-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:42:08.249 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 1 at bft.node.1/172.23.0.2:11000
2018-10-12 10:42:08.253 [nioEventLoopGroup-2-2] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:42:08.257 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 2 at bft.node.2/172.23.0.3:11000
2018-10-12 10:42:08.262 [nioEventLoopGroup-2-3] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:42:08.263 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 3 at bft.node.3/172.23.0.5:11000
2018-10-12 10:42:08.268 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Connecting to replica 4 at bft.node.4/172.23.0.12:11000
2018-10-12 10:42:08.270 [nioEventLoopGroup-2-4] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:42:08.273 [nioEventLoopGroup-2-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemClientSide - Channel active
2018-10-12 10:42:48.303 [main] INFO  bftsmart.tom.ServiceProxy - ###################TIMEOUT#######################
2018-10-12 10:42:48.303 [main] INFO  bftsmart.tom.ServiceProxy - Reply timeout for reqId=0, Replies received: 3
Exception in thread "main" java.lang.NullPointerException
	at bftsmart.reconfiguration.ViewManager.executeUpdates(ViewManager.java:115)
	at bftsmart.reconfiguration.VMServices.execute(VMServices.java:68)
	at bftsmart.reconfiguration.VMServices.addServer(VMServices.java:52)
	at bft.util.FabricVMServices.main(FabricVMServices.java:66)
```

Whether remove or add is ended whit a throw. Is't right ?

**Comment by jcs47** [comment]
Yes, the ./reconfigure script needs to be fixed. I'll work on it in the next days.

As for reconfiguring the set of frontends, unfortunately the codebase does not support it, because while BFT-SMaRt provides that functionality for replicas (which in the context of this ordering service are referred as "nodes"), frontends will need to have that feature built from scratch. That does not mean it cannot be implemented, but it will require more work that to fix the ./reconfigure script, and we will need to give priority to updating the ordering service to Fabric 1.3,

**Comment by learnergo** [comment]
Sorry,I don't think so.
Frontends are configured in the sys-channel and application-channel.It is easy to reconfigure both of them and I have tried successfully. I only have two things to do before using this in real production environment.First is the ability to upgrade the network and another is adding or removing the nodes.

I kown you are working on Fabric 1.3, but can you provide a Stable Ver of 1.2 ?

**Comment by jcs47** [comment]
> Sorry,I don't think so. Frontends are configured in the sys-channel and application-channel.It  is easy to reconfigure both of them and I have tried successfully.

And you did not run into problems over the fact that the new frontends do not have a full copy of the ledger? Because the main thing preventing frontends from supporting reconfiguration is having them fetch the ledger from other frontends. I am not aware about Fabric providing that functionality already, at least not from the documentation I've consulted or from the parts of the source code I am familiar with. If Fabric actually supports that already, the that makes everything easier for us.

>I kown you are working on Fabric 1.3, but can you provide a Stable Ver of 1.2 ?

First I need to know the exact steps to reproduce the problem you are having with reconfiguring the replica set. I tried to reproduce the problem already, but could not figure out how.

**Comment by learnergo** [comment]
> And you did not run into problems over the fact that the new frontends do not have a full copy of the ledger? 

Yes,I know. I solve it by copying the ledger from other frontend and restarting the new frontend.

> I tried to reproduce the problem already, but could not figure out how.

Maybe there is something wrong in my steps. I will repeat the experiment and you just need to answer the question "Is it reconfiguration feasible ?"

**Comment by jcs47** [comment]
> Yes,I know. I solve it by copying the ledger from other frontend and restarting the new frontend.

Unfortunately that isn't going to be feasible if you are dealing with a constant workload that will keep adding block to the ledger, unless you find a way to pause the system while transfering the ledger.

> Maybe there is something wrong in my steps. I will repeat the experiment and you just need to answer the question "Is it reconfiguration feasible ?"

Reconfiguration is feasible, but it is also one of the hardest features to implement.

**Comment by learnergo** [comment]
You mean  it can't reconfigure  now?

**Comment by jcs47** [comment]
What I meant is that since it is hard to implement, it takes time to find and solve all sorts of bugs.

**Comment by learnergo** [comment]
Today I used the ./reconfigure.sh and removed a node successfully.I am confuse.It has done or will be done. hahaha

**Comment by learnergo** [comment]
Today I built a network based on kafka mode and added a new orderer.I find it works fine.The new orderer could have all ledger and process tx.
