### ISSUE TITLE
Error： docker-compose  install  bft.node.X  

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#35]
2018-10-16 20:21:19.700 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-16 20:21:21.101 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)

What's the reason？
Thank you！

**Comment by jcs47** [comment]
In which circumstances does this problem occurs? Do you know how to reproduce this?

**Comment by Acmefocus** [comment]
Multiple machine installation occurs

**Comment by jcs47** [comment]
Yes, but does is message still appears even if  ordering node 0 is launched and executing? Can you tell me the steps it takes to reproduce this error?

**Comment by Acmefocus** [comment]
Yes, The error message still appears  after ordering node 0 and node x are launched and executing
This error occurs after starting a ordering  node or all ordering  nodes

**Comment by Acmefocus** [comment]
[root@localhost bft_smart]# docker logs bft.node.0
2018-10-19 02:28:50.349 [main] INFO  bft.BFTNode - Starting up ordering node with system channel bftchannel
2018-10-19 02:28:50.351 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-10-19 02:28:50.352 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-10-19 02:28:50.359 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - ID = 0
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - N = 4
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - F = 1
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Port = 11000
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - requestTimeout = 5000
2018-10-19 02:28:50.535 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - maxBatch = 400
2018-10-19 02:28:50.536 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Binded replica to IP address 172.20.0.2
2018-10-19 02:28:50.536 [main] INFO  bftsmart.tom.ServiceReplica - In current view: ID:0; F:1; Processes:0(bft.node.0/172.20.0.2:11000),1(bft.node.1/10.255.71.38:11000),2(bft.node.2/10.255.71.39:11000),3(bft.node.3/10.255.71.39:11000),


[root@localhost bft_smart]# docker logs bft.node.1
2018-10-19 02:29:23.659 [main] INFO  bft.BFTNode - Starting up ordering node with system channel bftchannel
2018-10-19 02:29:23.661 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-10-19 02:29:23.662 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-10-19 02:29:23.669 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-10-19 02:29:23.699 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
        at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
        at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
        at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
        at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
        at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
        at bft.BFTNode.<init>(BFTNode.java:190)
        at bft.BFTNode.main(BFTNode.java:262)
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - ID = 1
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - N = 4
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - F = 1
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Port = 11000
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - requestTimeout = 5000
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - maxBatch = 400
2018-10-19 02:29:23.868 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Binded replica to IP address 172.19.0.2
2018-10-19 02:29:23.868 [main] INFO  bftsmart.tom.ServiceReplica - In current view: ID:0; F:1; Processes:0(bft.node.0/10.255.71.37:11000),1(bft.node.1/172.19.0.2:11000),2(bft.node.2/10.255.71.39:11000),3(bft.node.3/10.255.71.39:11000),
2018-10-19 02:29:28.702 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:28.904 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:33.703 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:33.906 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:38.704 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:38.907 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:43.705 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:43.909 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:48.706 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:48.910 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:53.708 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:53.911 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:58.549 [nioEventLoopGroup-3-1] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Session Created, active clients=0
2018-10-19 02:29:58.578 [nioEventLoopGroup-3-1] ERROR b.c.c.netty.NettyTOMMessageDecoder - Failed to decode TOMMessage
java.io.EOFException: null
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at bftsmart.tom.core.messages.TOMMessage.rExternal(TOMMessage.java:243)
        at bftsmart.communication.client.netty.NettyTOMMessageDecoder.decode(NettyTOMMessageDecoder.java:144)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
2018-10-19 02:29:58.709 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:29:58.913 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:30:03.710 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:30:03.914 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:30:04.452 [nioEventLoopGroup-3-2] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Session Created, active clients=0
2018-10-19 02:30:04.492 [nioEventLoopGroup-3-2] ERROR b.c.c.netty.NettyTOMMessageDecoder - Failed to decode TOMMessage
java.io.EOFException: null

[root@localhost bft_smart]# docker logs bft.node.2
2018-10-19 02:38:54.305 [main] INFO  bft.BFTNode - Starting up ordering node with system channel bftchannel
2018-10-19 02:38:54.308 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-10-19 02:38:54.308 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-10-19 02:38:54.316 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-10-19 02:38:54.345 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
        at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
        at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
        at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
        at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
        at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
        at bft.BFTNode.<init>(BFTNode.java:190)
        at bft.BFTNode.main(BFTNode.java:262)
2018-10-19 02:38:59.348 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:04.349 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:09.351 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:14.352 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:19.353 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:24.354 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:29.355 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)

[root@localhost bft_smart]# docker logs bft.node.3
2018-10-19 02:38:58.787 [main] INFO  bft.BFTNode - Starting up ordering node with system channel bftchannel
2018-10-19 02:38:58.789 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-10-19 02:38:58.789 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-10-19 02:38:58.795 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-10-19 02:38:58.821 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
        at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
        at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
        at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
        at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
        at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
        at bft.BFTNode.<init>(BFTNode.java:190)
        at bft.BFTNode.main(BFTNode.java:262)
2018-10-19 02:39:03.825 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:08.826 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:13.828 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:18.829 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:23.830 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:28.831 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:33.832 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:38.833 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:43.834 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:48.835 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-10-19 02:39:53.836 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)

**Comment by jcs47** [comment]
According to the logs, each individual replica is binding itself to a different IP address than the one that the other replicas are obtaining (e.g., replica 0 binding to IP address 172.19.0.2 yet the other replicas try to connect to it on IP address 10.255.71.37).

I don't know the exact reason why that is happening, but you might be able to solve the problem by explicitly telling each replica the IP address to which they should bind. You can do it by editing the `system.communication.bindaddress` parameter at the `config/system.config` file. For instance, in the case of replica 0, the other replicas attempt to connect to it at 10.255.71.37, so you would set `system.communication.bindaddress` to that address. You  can check to what addresses each replicas is trying to connect to others in the following message:

```
2018-10-19 02:28:50.536 [main] INFO bftsmart.tom.ServiceReplica - In current view: ID:0; F:1; Processes:0(bft.node.0/172.20.0.2:11000),1(bft.node.1/10.255.71.38:11000),2(bft.node.2/10.255.71.39:11000),3(bft.node.3/10.255.71.39:11000)
```

If you were following the quick start guide and need to know how to supply a different `config/system.config` file to the containers, check (this guide)[https://github.com/bft-smart/fabric-orderingservice/wiki/Configuring-a-deployment-v1.3].

**Comment by Acmefocus** [comment]
Thank you！  This problem has been solved！ Because bft.node.x port is not open!

**Comment by robertrobertsgdms** [comment]
@lifu568 I am having the same issue. Can you explain how you open the ports for node.x?
Do you do it in the hosts.config or in the docker file?

**Comment by Acmefocus** [comment]
Please refer to the link below
https://github.com/lifu568/fabric-orderingservice/tree/release-1.3/multihostInstall

**Comment by lifu568** [comment]
Please refer to the link below：
https://github.com/lifu568/fabric-orderingservice/tree/release-1.3/multihostInstall




------------------ 原始邮件 ------------------
发件人: "robertrobertsgdms"<notifications@github.com>;
发送时间: 2019年9月16日(星期一) 晚上9:49
收件人: "bft-smart/fabric-orderingservice"<fabric-orderingservice@noreply.github.com>;
抄送: "南风(strong)"<107723772@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [bft-smart/fabric-orderingservice] Error： docker-compose  install  bft.node.X   (#35)




@lifu568 I am having the same issue. Can you explain how you open the ports for node.x?
 Do you do it in the hosts.config or in the docker file?
