### ISSUE TITLE
Error  CRIT 010 Could not append configuration block:

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#36]
2018-10-17 10:04:33.017 UTC [msp] DeserializeIdentity -> INFO 00a Obtaining identity
2018-10-17 10:04:33.023 UTC [msp] DeserializeIdentity -> INFO 00b Obtaining identity
2018-10-17 10:04:33.039 UTC [msp] DeserializeIdentity -> INFO 00c Obtaining identity
2018-10-17 10:04:34.023 [Thread-11] INFO  bft.BFTProxy - Received block # 1
2018-10-17 10:04:34.093 UTC [orderer/bftsmart] newChain -> INFO 00d Creating new bftsmart chain with ID 'channel47'
2018-10-17 10:04:34.093 UTC [orderer/commmon/multichannel] newChain -> INFO 00e Created and starting new chain channel47
2018-10-17 10:04:34.093 UTC [orderer/bftsmart] Start -> INFO 00f Starting new bftsmart chain with ID 'channel47'
2018-10-17 10:04:34.095 UTC [orderer/bftsmart] appendToChain -> CRIT 010 Could not append configuration block: Block should have had previous hash of 2a47d68bbfd988acb4b4feca3a1ce461cbeeabe3babeb6f4b6b496984876204e but was af96dbdf7e20915c6687ba74534248906a6bd4c384687266c73a9fa2c877e51b
2018-10-17 10:04:34.095 [main] INFO  bft.BFTProxy - Read BatchTimeout: 2000000000
2018-10-17 10:04:34.100 [main] INFO  bft.BFTProxy - Setting up system for new channel 'channel47'
panic: Could not append configuration block: Block should have had previous hash of 2a47d68bbfd988acb4b4feca3a1ce461cbeeabe3babeb6f4b6b496984876204e but was af96dbdf7e20915c6687ba74534248906a6bd4c384687266c73a9fa2c877e51b

goroutine 10 [running]:
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panicf(0xc42025d170, 0x1083721, 0x28, 0xc4204dd1f0, 0x1, 0x1)
        /go/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:194 +0x126
github.com/hyperledger/fabric/orderer/consensus/bftsmart.(*chain).appendToChain(0xc4201654c0)
        /go/src/github.com/hyperledger/fabric/orderer/consensus/bftsmart/consensus.go:525 +0x268
created by github.com/hyperledger/fabric/orderer/consensus/bftsmart.(*chain).Start
        /go/src/github.com/hyperledger/fabric/orderer/consensus/bftsmart/consensus.go:179 +0xa8b

**Comment by jcs47** [comment]
Are you sure you are using the same genesis block file both at the frontends and ordering nodes? If the file is indeed the same, check if the General>GenesisMethod parameters in the orderer.yaml file is set to "file".

**Comment by Acmefocus** [comment]
It's ok ， Thank you！
