### ISSUE TITLE
ERROR BFT.NODE 

### ISSUE THREAD

**Issue by Acmefocus** [jcs47/hyperledger-bftsmart#42]
2018-11-05 13:30:34.324 [Delivery Thread] ERROR bft.BFTNode - Failed to fetch snapshot
java.io.NotSerializableException: bft.util.MSPManager$OUIdentifier
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at java.util.TreeMap.writeObject(TreeMap.java:2438)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at bft.util.MSPManager.serialize(MSPManager.java:719)
        at bft.BFTNode.getSnapshot(BFTNode.java:383)
        at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:131)
        at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:72)
        at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:443)
        at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:303)
        at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:234)

Hi,  How to fix this error

**Comment by jcs47** [comment]
I fixed an exception very similar to this one some weeks ago. Try re-pulling the images from the docker repository.

**Comment by Acmefocus** [comment]
Thanks
