### ISSUE TITLE
Failed to connect to replica

### ISSUE THREAD

**Issue by HaoJiawang** [jcs47/hyperledger-bftsmart#47]
```
2018-11-24 13:28:31.323 [main] INFO  bft.BFTNode - Starting up ordering node with system channel testchainid
2018-11-24 13:28:31.343 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-11-24 13:28:31.344 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-11-24 13:28:31.350 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-11-24 13:28:31.406 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
	at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
2018-11-24 13:28:31.677 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - ID = 1
2018-11-24 13:28:31.677 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - N = 4
2018-11-24 13:28:31.678 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - F = 1
2018-11-24 13:28:31.678 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Port = 11000
2018-11-24 13:28:31.678 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - requestTimeout = 5000
2018-11-24 13:28:31.678 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - maxBatch = 400
2018-11-24 13:28:31.678 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Binded replica to IP address 127.0.0.1
2018-11-24 13:28:31.678 [main] INFO  bftsmart.tom.ServiceReplica - In current view: ID:0; F:1; Processes:0(/127.0.0.1:11010),1(/127.0.0.1:11000),2(/127.0.0.1:11020),3(/127.0.0.1:11030),
2018-11-24 13:28:36.437 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
2018-11-24 13:28:36.755 [Sender for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection refused (Connection refused)
```

0.bft.node can print “INFO  bftsmart.tom.core.DeliveryThread - Retrieving State ” normally，but when I run 1.bft.node errors occur. I am sure that my configure files are right.

**Comment by jcs47** [comment]
According to the logs, the replicas are still binding to the loopback address, which makes replica 1 is try to connect to replica 0 at that address. My guess is that the domains are being resolved into the lookback addresses. Try using the actual IP addresses to which each replica should bind to (instead of the domains).

**Comment by HaoJiawang** [comment]
@jcs47 Thank you for help, I use 127.0.0.1 as the IP address to each replica with different port number in host.config, but it doesn't work.

**Comment by jcs47** [comment]
If you are executing within docker, you cannot use the loopback address, because each container works as if it were in its own machine. You need to supply the virtual IP addresses of the containers instead. Typically each docker container is assigned an IP addresses starting with 172.17.0.2.

**Comment by HaoJiawang** [comment]
@jcs47 Thank you again for help,  I use 172.17.0.2 as the new IP address, but there are still some errors. I also tried to use 172.17.0.3 for the second replica, it has the same error, what  can I do next?
```
2018-11-26 04:53:30.723 [main] INFO  bft.BFTNode - Starting up ordering node with system channel testchainid
2018-11-26 04:53:30.725 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-11-26 04:53:30.725 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-11-26 04:53:30.732 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-11-26 04:55:41.193 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
	at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
2018-11-26 04:55:41.687 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - ID = 1
2018-11-26 04:55:41.688 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - N = 4
2018-11-26 04:55:41.688 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - F = 1
2018-11-26 04:55:41.688 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Port = 11010
2018-11-26 04:55:41.689 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - requestTimeout = 5000
2018-11-26 04:55:41.689 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - maxBatch = 400
2018-11-26 04:55:41.689 [main] INFO  b.c.c.n.NettyClientServerCommunicationSystemServerSide - Binded replica to IP address 172.19.0.3
2018-11-26 04:55:41.689 [main] INFO  bftsmart.tom.ServiceReplica - In current view: ID:0; F:1; Processes:0(/172.17.0.2:11000),1(/172.17.0.2:11010),2(/172.17.0.2:11020),3(/172.17.0.2:11030),
2018-11-26 04:57:56.355 [Receiver for 0] ERROR b.c.server.ServerConnection - Impossible to reconnect to replica 0: Connection timed out (Connection timed out)
2018-11-26 04:58:14.105 [Thread-3] INFO  bftsmart.tom.util.ShutdownHookThread 
```

**Comment by jcs47** [comment]
Now you are assigning all replicas the same IP. Each container has a different IP. You can see to which address a replica is binding to by checking the ` - Binded replica to IP address xxx.xxx.xxx.xxx` message in your logs. For instance, replica 1 is binding to address 172.19.0.3. Based on the logs, my guess is that each replica is binding to the following addresses:

replica 0 - 172.19.0.2
replica 1 - 172.19.0.3
replica 2 - 172.19.0.4
replica 3 - 172.19.0.5

Also, you should also try to simply using the name of the containers in place of the IP addresses (which is the approach that typically works the best). Following the pattern you established in the first post, you should use these in the `hosts.config` file:

replica 0 - 0.bft.node
replica 1 - 1.bft.node
replica 2 - 2.bft.node
replica 3 - 3.bft.node

**Comment by HaoJiawang** [comment]
@jcs47  Thanks a lot
