### ISSUE TITLE
Failed to initialize replica-to-replica communication system

### ISSUE THREAD

**Issue by seuho2003** [jcs47/hyperledger-bftsmart#49]
Hello, I'm really sorry for lots of questions I've had.
But I really hope I can bring up this fully functioning network successfully.

As I finished configuring my network, and tried to bring up the first ordering node(bftnode0) with this command:
$docker run -i -t --rm --network=bft_network --name=0.node.bft -e NODE_CONFIG_DIR=/bft-config/config/ -v .../fabric-samples/docker_images/orderingnode_material/:/bft-config/   bftsmart/fabric-orderingnode:amd64-1.3.0 0

This error message is shown and it says failed to initialize replica-to-replica commuinication system:
2018-11-26 15:00:52.720 [main] INFO  bft.BFTNode - Starting up ordering node with system channel bftchannel
2018-11-26 15:00:52.734 [main] INFO  bft.BFTNode - This is the signature algorithm: SHA256withECDSA
2018-11-26 15:00:52.734 [main] INFO  bft.BFTNode - This is the hash algorithm: SHA2
2018-11-26 15:00:52.787 [main] INFO  b.r.ServerViewController - Creating current view from configuration file
2018-11-26 15:00:53.764 [main] ERROR bftsmart.tom.ServiceReplica - Failed to initialize replica-to-replica communication system
java.lang.NullPointerException: null
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:90)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
Exception in thread "main" java.lang.RuntimeException: Unable to build a communication system.
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:154)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)

When I ignored that error message and tried to bring up the second replica(bftnode1),

2018-11-26 15:02:54.930 [Receiver for 0] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.UnknownHostException: bft.node.0
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at bftsmart.communication.server.ServerConnection.reconnect(ServerConnection.java:288)
	at bftsmart.communication.server.ServerConnection.waitAndConnect(ServerConnection.java:437)
	at bftsmart.communication.server.ServerConnection.access$1200(ServerConnection.java:57)
	at bftsmart.communication.server.ServerConnection$ReceiverThread.run(ServerConnection.java:541)

I can see this error message keep on appearing on the console.

I really need your help. Could you please help me resolve this error?

Thank you!

**Comment by jcs47** [comment]
Can you show me the log messages that pop up after the exception is printed? Those messages have information about the addresses to each replicas are trying to connect, as well as to which address they are binding. That might give clues to what is happening.

**Comment by seuho2003** [comment]
There was no message after "Exception in thread "main"....."(in bftnode0), and 

2018-11-26 15:01:53.646 [main] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.UnknownHostException: bft.node.0
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at bftsmart.communication.server.ServerConnection.<init>(ServerConnection.java:103)
	at bftsmart.communication.server.ServersCommunicationLayer.getConnection(ServersCommunicationLayer.java:176)
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:83)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
2018-11-26 15:01:53.650 [main] ERROR bftsmart.tom.ServiceReplica - Failed to initialize replica-to-replica communication system
java.lang.NullPointerException: null
	at bftsmart.communication.server.ServersCommunicationLayer.<init>(ServersCommunicationLayer.java:90)
	at bftsmart.communication.ServerCommunicationSystem.<init>(ServerCommunicationSystem.java:68)
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:151)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
Exception in thread "main" java.lang.RuntimeException: Unable to build a communication system.
	at bftsmart.tom.ServiceReplica.init(ServiceReplica.java:154)
	at bftsmart.tom.ServiceReplica.<init>(ServiceReplica.java:139)
	at bft.BFTNode.<init>(BFTNode.java:190)
	at bft.BFTNode.main(BFTNode.java:262)
2018-11-26 15:01:58.650 [Receiver for 0] ERROR b.c.server.ServerConnection - Failed to connect to replica
java.net.UnknownHostException: bft.node.0
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at bftsmart.communication.server.ServerConnection.reconnect(ServerConnection.java:288)
	at bftsmart.communication.server.ServerConnection.waitAndConnect(ServerConnection.java:437)
	at bftsmart.communication.server.ServerConnection.access$1200(ServerConnection.java:57)
	at bftsmart.communication.server.ServerConnection$ReceiverThread.run(ServerConnection.java:541)
2018-11-26 15:02:03.867 [Receiver for 0] ERROR b.c.server.ServerConnection - Failed to connect to replica


I can see this error message in bftnode1.
