### ISSUE TITLE
Error when running ./startReplica.sh

### ISSUE THREAD

**Issue by gmitaros** [jcs47/hyperledger-bftsmart#9]
Hello here are the steps i followed installing and running hyperledger-bftsmart.
i did git clone https://github.com/jcs47/fabric
into the path $GOPATH/src/github.com/hyperledger/
installed all the Pre-requisites for the Hyperledger
Also installed JUDS library
Then i did these
cd $GOPATH/src/github.com/hyperledger/fabric/
sudo ./devenv/setupUbuntuOnPPC64le.sh
make dist-clean peer orderer configtxgen
export FABRIC_CFG_PATH=$GOPATH/src/github.com/hyperledger/fabric/sampleconfig/
Also i donfiguerd the absolute paths for CERTIFICATE  and PRIVKEY.
and then:
cd $GOPATH//src/github.com/hyperledger/hyperledger-bftsmart 
i run 
ant and then
./startReplica.sh 0

and i get this error
```
mitaros@dsg2:~/GoProjects/src/github.com/hyperledger/hyperledger-bftsmart$ sudo ./startReplica.sh 0
Exception in thread "main" org.bouncycastle.openssl.PEMException: unable to convert key pair: EC KeyFactory not available
	at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyPair(Unknown Source)
	at bft.BFTNode.getPemPrivateKey(BFTNode.java:797)
	at bft.BFTNode.loadConfig(BFTNode.java:197)
	at bft.BFTNode.<init>(BFTNode.java:130)
	at bft.BFTNode.main(BFTNode.java:223)
Caused by: java.security.NoSuchAlgorithmException: EC KeyFactory not available
	at java.security.KeyFactory.<init>(java.base@9-internal/KeyFactory.java:138)
	at java.security.KeyFactory.getInstance(java.base@9-internal/KeyFactory.java:180)
	at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createKeyFactory(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyFactory(Unknown Source)
	... 5 more
mitaros@dsg2:~/GoProjects/src/github.com/hyperledger/hyperledger-bftsmart$ 
```

**Comment by gmitaros** [comment]
The solution was to add **hyperledger-bftsmart** into the $GOPATH//src/github.com/hyperledger/fabric
